version: "3.0"
services:
    backend:
        build: .
        ports:
            - "4000:4000"
        links:
            - "mysql:mysql"
        environment:
            DB_HOST: mysql
            DB_USER: root
            DB_PASSWORD: password
            DB_DATABASE: test
    mysql:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: test
