name: Backend integration tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build the docker-compose stack
      run: (cd backend; docker-compose build)
    
    - name: Run tests
      run: (cd backend; docker-compose up -d; sleep 5s; sh test.sh)
